viloca:
  tiling_bed: resources/vp1.bed
vpipe:
  general:
      virus_base_config: ""
      aligner: minimap
      preprocessor: skip
      temp_prefix: /cluster/scratch/lfuhrmann/temp

  input:
      reference: resources/polio_ref.fasta
      datadir: resources/samples/
      samples_file: config/samples.tsv
      paired: false

  output:
      trim_primers: false
      snv: false
      local: false
      global: false
      visualization: false
      QA: false
      diversity: false

  minimap_align:
      preset: map-ont
