fname_reference: resources/MT107528.1.fasta
fname_insert_bed: /cluster/project/pangolin/work-viloca/RSV-wastewater-sample-processing-VILOCA/RSVB_inserts_400_V2.1.bed
fname_samples: config/samples.csv
dir_path_samples: /cluster/project/pangolin/work-viloca/RSV-wastewater-sample-processing-VILOCA/results-after-V-pipe/results/
